---

name: main-build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: build
        shell: bash
        run: |
          pip install -r requirements.txt && \
          bdast ./entrypoint.yaml build -v

